#spring:
#  application:
#    name: simple-blog-system
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/simple_blog_system_db}
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:257890}
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#upload-dir: ./uploads
#
#app:
#  jwt-secret: a59c7077a4fc78d218fcd585b79d78fad473c19c221c3bd6214907886966bb21
#  jwt-expiration-milliseconds: 604800000
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    operations-sorter: alpha
#    tags-sorter: alpha
#    filter: true
#    display-tag-groups: true
#  api-docs:
#    path: /v3/api-docs
